# Generated by Django 3.2 on 2022-09-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogcomment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
