# Generated by Django 3.2 on 2022-09-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogcomment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='comment_reply',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='reply',
        ),
    ]
