# Generated by Django 3.2 on 2022-09-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentreply',
            name='post_type',
            field=models.CharField(default=5, max_length=120),
            preserve_default=False,
        ),
    ]
