# Generated by Django 3.2 on 2022-09-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcommentreply_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='post_type',
            new_name='blog_post_id',
        ),
    ]
