# Generated by Django 3.2 on 2022-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_rename_name_contact_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fname',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
