# Generated by Django 3.2 on 2022-09-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.CharField(default=1000, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default=200, max_length=120),
            preserve_default=False,
        ),
    ]
