# Generated by Django 3.2 on 2022-09-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20220928_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='body',
            field=models.CharField(default=1000, max_length=1000),
            preserve_default=False,
        ),
    ]
