# Generated by Django 3.2 on 2022-10-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='amb_membership',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='appointed_trustees',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='associate_membership',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='founding_trustees',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='governing_board',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='project_facilitator',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='volunteer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
